---
spring:
  application:
    name: rastibot-user-service
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DBNAME}
    username: rastibot-user-service
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: on
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

logging:
  config: ${LOGGING_CONFIG}
  level:
    root: INFO
    com.sbrati: INFO

server:
  port: 9294